export const room_list = [
    {
        roomType: "K",
        roomNumber: 1,
        roomRate: 25.00,
        totalCharge: 250.0,
        payment: 250.0,
        balance: 0.0,
        availability: false,
        maintainance: false,
        checkin: "2021/10/15",
        checkout: "2021/10/16",
        guestID: "Q6733337",
    },
    {
        roomType: "DQ",
        roomNumber: 2,
        roomRate: 20.00,
        totalCharge: 200.0,
        payment: 200.0,
        balance: 0.0,
        availability: true,
        maintainance: true,
        checkin: "none",
        checkout: "none",
        guestID: "none",
    },
    {
        roomType: "DBK",
        roomNumber: 3,
        roomRate: 30.00,
        totalCharge: 600.0,
        payment: 350.0,
        balance: 250.0,
        availability: false,
        maintainance: false,
        checkin: "2021/10/15",
        checkout: "2021/10/18",
        guestID: "O3933089",
    },
    {
        roomType: "S",
        roomNumber: 4,
        roomRate: 15.00,
        totalCharge: 300.0,
        payment: 100.0,
        balance: 200.0,
        availability: false,
        maintainance: false,
        checkin: "2021/10/15",
        checkout: "2021/10/17",
        guestID: "D4766458",
    },
    {
        roomType: "S",
        roomNumber: 4,
        roomRate: 15.00,
        totalCharge: 300.0,
        payment: 300.0,
        balance: 0.0,
        availability: true,
        maintainance: false,
        checkin: "none",
        checkout: "none",
        guestID: "none",
    },
    {
        roomType: "K",
        roomNumber: 5,
        roomRate: 25.00,
        totalCharge: 250.0,
        payment: 250.0,
        balance: 0.0,
        availability: true,
        maintainance: true,
        checkin: "none",
        checkout: "none",
        guestID: "none",
    },
    {
        roomType: "DBK",
        roomNumber: 6,
        roomRate: 30.00,
        totalCharge: 300.0,
        payment: 300.0,
        balance: 0.0,
        availability: false,
        maintainance: false,
        checkin: "none",
        checkout: "none",
        guestID: "none",
    },
]